import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../data/finance_models.dart';
import '../data/finance_repository.dart';

class FinanceAnalyticsPage extends StatefulWidget { const FinanceAnalyticsPage({super.key}); @override State<FinanceAnalyticsPage> createState() => _FinanceAnalyticsPageState(); }
class _FinanceAnalyticsPageState extends State<FinanceAnalyticsPage> {
  final _repo = FinanceRepository(Supabase.instance.client); final _money = NumberFormat.currency(locale: 'en_IN', symbol: '₹', decimalDigits: 0);
  List<FinanceTransaction> _items = []; int _days = 90; bool _loading = true;
  @override void initState() { super.initState(); _load(); }
  Future<void> _load() async { setState(() => _loading = true); final rows = await _repo.listTransactions(from: DateTime.now().subtract(Duration(days: _days))); if (mounted) setState(() { _items = rows; _loading = false; }); }
  @override Widget build(BuildContext context) { final income = _items.where((x) => x.type == 'income').fold(0.0, (a, x) => a + x.amount); final expense = _items.where((x) => x.type == 'expense').fold(0.0, (a, x) => a + x.amount); final grouped = <String, List<FinanceTransaction>>{}; for (final x in _items) { final k = DateFormat('MMM yy').format(x.transactionDate); grouped.putIfAbsent(k, () => []).add(x); } final months = grouped.entries.toList().reversed.toList(); final maxY = ([income, expense, ...months.expand((e) => e.value.map((x) => x.amount))].fold(1.0, (a, b) => a > b ? a : b)) * 1.2;
    return Scaffold(appBar: AppBar(title: const Text('Finance analytics')), body: _loading ? const Center(child: CircularProgressIndicator()) : ListView(padding: const EdgeInsets.all(20), children: [Text('Income vs expense', style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800)), const SizedBox(height: 12), SegmentedButton<int>(segments: const [ButtonSegment(value: 30, label: Text('30d')), ButtonSegment(value: 90, label: Text('90d')), ButtonSegment(value: 365, label: Text('1y'))], selected: {_days}, onSelectionChanged: (v) { setState(() => _days = v.first); _load(); }), const SizedBox(height: 18), Card(child: Padding(padding: const EdgeInsets.fromLTRB(10, 20, 20, 16), child: SizedBox(height: 280, child: BarChart(BarChartData(maxY: maxY, gridData: const FlGridData(show: true), borderData: FlBorderData(show: false), titlesData: FlTitlesData(bottomTitles: AxisTitles(sideTitles: SideTitles(showTitles: true, getTitlesWidget: (v, meta) { final i = v.toInt(); if (i < 0 || i >= months.length) return const SizedBox(); return SideTitleWidget(meta: meta, child: Text(months[i].key, style: const TextStyle(fontSize: 10))); })), leftTitles: const AxisTitles(sideTitles: SideTitles(showTitles: true, reservedSize: 46)), topTitles: const AxisTitles(sideTitles: SideTitles(showTitles: false)), rightTitles: const AxisTitles(sideTitles: SideTitles(showTitles: false))), barGroups: List.generate(months.length, (i) { final incomeM = months[i].value.where((x) => x.type == 'income').fold(0.0, (a, x) => a + x.amount); final expenseM = months[i].value.where((x) => x.type == 'expense').fold(0.0, (a, x) => a + x.amount); return BarChartGroupData(x: i, barsSpace: 4, barRods: [BarChartRodData(toY: incomeM, width: 9), BarChartRodData(toY: expenseM, width: 9)]); })))))), const SizedBox(height: 18), Row(children: [Expanded(child: Card(child: ListTile(title: const Text('Total income'), subtitle: Text(_money.format(income)), leading: const Icon(Icons.south_west_rounded)))), const SizedBox(width: 10), Expanded(child: Card(child: ListTile(title: const Text('Total expense'), subtitle: Text(_money.format(expense)), leading: const Icon(Icons.north_east_rounded))))]), const SizedBox(height: 10), Card(child: ListTile(title: const Text('Net profit'), subtitle: Text(_money.format(income - expense), style: const TextStyle(fontWeight: FontWeight.w800)), leading: const Icon(Icons.account_balance_wallet_rounded))), const SizedBox(height: 18), Text('Expense categories', style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w800)), ..._categoryRows(), const SizedBox(height: 20), const Text('Analytics are calculated from your recorded ledger entries.'))])); }
  List<Widget> _categoryRows() { final totals = <String, double>{}; for (final x in _items.where((x) => x.type == 'expense')) { totals[x.category] = (totals[x.category] ?? 0) + x.amount; } final entries = totals.entries.toList()..sort((a, b) => b.value.compareTo(a.value)); return entries.take(8).map((e) => ListTile(title: Text(e.key), trailing: Text(_money.format(e.value), style: const TextStyle(fontWeight: FontWeight.w700)))).toList(); }
}
