create table if not exists public.iot_devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  device_type text not null default 'esp32',
  device_key text not null unique,
  field_id uuid references public.fields(id) on delete set null,
  is_online boolean not null default false,
  last_seen timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.iot_readings (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.iot_devices(id) on delete cascade,
  soil_moisture numeric,
  temperature numeric,
  humidity numeric,
  water_level numeric,
  pump_on boolean,
  recorded_at timestamptz not null default now()
);

create index if not exists iot_devices_user_idx on public.iot_devices(user_id);
create index if not exists iot_readings_device_time_idx on public.iot_readings(device_id, recorded_at desc);
alter table public.iot_devices enable row level security;
alter table public.iot_readings enable row level security;
drop policy if exists iot_devices_own on public.iot_devices;
create policy iot_devices_own on public.iot_devices for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists iot_readings_own on public.iot_readings;
create policy iot_readings_own on public.iot_readings for select to authenticated using (exists (select 1 from public.iot_devices d where d.id = device_id and d.user_id = (select auth.uid())));
grant select, insert, update, delete on public.iot_devices to authenticated;
grant select on public.iot_readings to authenticated;
do $$ begin alter publication supabase_realtime add table public.iot_devices; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.iot_readings; exception when duplicate_object then null; end $$;
